baseURL = "https://danielmrcl.dev"
languageCode = "en-us"
title = "Daniel Marcelo"
copyright = "Me"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[markup]
[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "gruvbox"
tabWidth = 4

[params]
rss = false
tocInline = true
description = "Software Engineer | Back End Developer | Java 8+ | Microservices"
tagsOverview = true
show_updated = true
showReadTime = false
pubkey = "https://danielmrcl.dev/gpg.asc"
bitcoin = "bc1qmu7ulnq7uyc474jwcupf9y5jx7t0r63hr73tww"
mastodon = "https://mastodon.social/@danielmrcl" # TODO check if can be removed

[params.comments]
enabled = false

[[params.social]]
name = "email"
link = "mailto:dan@danielmrcl.dev"
[[params.social]]
name = "linkedin"
link = "https://click.danielmrcl.dev/linkedin"
[[params.social]]
name = "github"
link = "https://click.danielmrcl.dev/github"
[[params.social]]
name = "gitlab"
link = "https://click.danielmrcl.dev/gitlab"
[[params.social]]
name = "mastodon"
link = "https://mastodon.social/@danielmrcl"
